language: node_js
dist: trusty
sudo: required
node_js: stable
install:
  - npm install -g bower pulp purescript
  - npm install
  - bower install
  - pulp build
script:
  - npm run -s build
  - pulp test
after_success:
- >-
  test $TRAVIS_TAG &&
  echo $GITHUB_TOKEN | pulp login &&
  echo y | pulp publish --no-push
